### PR TITLE
Authentication implementation with new project structure

### PR DESCRIPTION
**Pull request by alexaib2002**
This branch solves the merge conflicts that were made after #38 with the new authentication features

### CODE REVIEW

**Comment by aleexgheorghe** [comment]
It looks great to me!

**Review by aleexgheorghe — APPROVED** [review]

**Comment by Jkutkut** [comment]
There was a bug fixed with the `db-v0.9.04` of the API. Please update this with this change.

**Review by Jkutkut — CHANGES_REQUESTED** [review]
Please, use the version of the API `db-v0.9.06`

**Comment by alexaib2002** [comment]
Merged with API `v0.9.06` branch

**Review by Jkutkut — APPROVED** [review]

**Pull request merged**
