### PR TITLE
DB booking insertion

### PR DESCRIPTION
**Pull request by alexaib2002**
With this branch merged, the app will be able to insert data into the DB. Should also mark the release of version 0.3

### CODE REVIEW

**Comment by alexaib2002** [comment]
- Stalled development until #35 is implemented

**Comment by Jkutkut** [comment]
Ready to rock now! The version `db-v0.9.06` handles this feature and the use of Firebase Storage

**Comment by alexaib2002** [comment]
PR marked ready for review as all the required methods have been implemented

**Review by Jkutkut — APPROVED** [review]
Everything OK

**Comment by Jkutkut** [comment]
Conflict with main fixed

**Review by aleexgheorghe — APPROVED** [review]

**Pull request merged**
